services:
  - type: web
    name: gamma-ai-watermark-remover
    runtime: docker
    repo: https://github.com/danielxxomg2/gamma-pdf-watermark-remover
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: '3.10'
      - key: PORT
        value: 8000
    autoDeploy: false